//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baberShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFOR_SHOP
    {
        public int ID_SHOP { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string FACEBOOK { get; set; }
        public string ZALO { get; set; }
        public string INSTAGRAM { get; set; }
        public string TIMEOPEN_DAILY { get; set; }
        public string ADDRESS_SHOP { get; set; }
    }
}
