//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baberShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFOUSER
    {
        public int ID_INFO_USER { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS_USER { get; set; }
        public string AVT_USER { get; set; }
        public string LINK_FB_USER { get; set; }
    
        public virtual ACCOUNT_USER ACCOUNT_USER { get; set; }
    }
}
