//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baberShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public int ID_MENU { get; set; }
        public string NAME_MENU { get; set; }
        public Nullable<System.DateTime> DATETIME_MENU { get; set; }
        public string LINK { get; set; }
        public Nullable<bool> STATUS_MENU { get; set; }
    }
}
