//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baberShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public int ID_NHANVIEN { get; set; }
        public string NAME_NHANVIEN { get; set; }
        public string SEX { get; set; }
        public string SKILL { get; set; }
        public string AVT { get; set; }
        public string PHONE { get; set; }
        public string LINK_FB { get; set; }
        public string LINK_INSTAGRAM { get; set; }
        public string DESCRIPSTION_NV { get; set; }
    }
}
