//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baberShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_SHOP
    {
        public int ID_SERVICE { get; set; }
        public string NAME_SERVICE { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string IMG { get; set; }
        public string DESCRIPSTION { get; set; }
        public Nullable<bool> STATUS_SERVICE { get; set; }
    }
}
